
CREATE TABLE Game (
  id SERIAL PRIMARY KEY,
  playerId INT NOT NULL,
  score INT NOT NULL,
  levelId INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_player FOREIGN KEY(playerId) REFERENCES Player(id) ON DELETE CASCADE,
  CONSTRAINT fk_level FOREIGN KEY(levelId) REFERENCES Level(id) ON DELETE CASCADE
);
