
CREATE TABLE Player (
  id SERIAL PRIMARY KEY,
  firstName VARCHAR(500) NOT NULL,
  lastName VARCHAR(500) NOT NULL,
  userName VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(500) NOT NULL,
  gender VARCHAR(10) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
