
CREATE TABLE Ranking (
  id SERIAL PRIMARY KEY,
  playerId INT NOT NULL,
  scores INT NOT NULL,
  rank VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_player_ranking FOREIGN KEY(playerId) REFERENCES Player(id) ON DELETE CASCADE
);
